In [1]:
from CybORG import CybORG
from CybORG.Simulator.Scenarios import EnterpriseScenarioGenerator
# from CybORG.Agents.Wrappers import BlueFixedActionWrapper
from CybORG.Agents.Wrappers import BlueFlatWrapper
from rich import print

/home/aquacat1220/.local/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
2025-06-17 18:25:05,922	INFO util.py:154 -- Missing packages: ['ipywidgets']. Run `pip install -U ipywidgets`, then restart the notebook server for rich notebook output.
2025-06-17 18:25:08,870	INFO util.py:154 -- Missing packages: ['ipywidgets']. Run `pip install -U ipywidgets`, then restart the notebook server for rich notebook output.


In [2]:
sg = EnterpriseScenarioGenerator()
cyborg = CybORG(scenario_generator=sg)
# env = BlueFixedActionWrapper(env=cyborg)
env = BlueFlatWrapper(env=cyborg)

In [3]:
obs, _ = env.reset()

In [4]:
print(type(obs))
print(obs.keys())

<class 'dict'>

dict_keys(['blue_agent_0', 'blue_agent_1', 'blue_agent_2', 'blue_agent_3', 'blue_agent_4'])

In [8]:
print(env.observation_spaces())

{
    'blue_agent_0': MultiDiscrete([3 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]),
    'blue_agent_1': MultiDiscrete([3 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]),
    'blue_agent_2': MultiDiscrete([3 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]),
    'blue_agent_3': MultiDiscrete([3 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]),
    'blue_agent_4': MultiDiscrete([3 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2])
}

In [7]:
ba0_obs = obs['blue_agent_0']
print(type(ba0_obs))
print(ba0_obs)

<class 'numpy.ndarray'>

[0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]

In [6]:
print(ba0_obs['restricted_zone_a_subnet_server_host_0'])

{
    'Interface': [
        {
            'interface_name': 'eth0',
            'ip_address': IPv4Address('10.0.215.254'),
            'Subnet': IPv4Network('10.0.215.0/24')
        }
    ],
    'Sessions': [
        {
            'session_id': 8,
            'username': 'ubuntu',
            'timeout': 0,
            'PID': 4956,
            'Type': <SessionType.UNKNOWN: 1>,
            'agent': 'blue_agent_0'
        }
    ],
    'Processes': [{'PID': 4956, 'username': 'ubuntu'}],
    'User Info': [{'username': 'root', 'Groups': [{'GID': 0}]}, {'username': 'user', 'Groups': [{'GID': 1}]}],
    'System info': {
        'Hostname': 'restricted_zone_a_subnet_server_host_0',
        'OSType': <OperatingSystemType.LINUX: 3>,
        'OSDistribution': <OperatingSystemDistribution.UBUNTU: 8>,
        'OSVersion': <OperatingSystemVersion.UNKNOWN: 1>,
        'Architecture': <Architecture.x64: 2>,
        'position': array([0., 0.])
    }
}

In [7]:
print(env.action_space(agent_name="blue_agent_0"))
print(env.action_labels(agent_name="blue_agent_0"))

Discrete(82)

[
    'Analyse restricted_zone_a_subnet_server_host_0',
    'Analyse restricted_zone_a_subnet_server_host_1',
    'Analyse restricted_zone_a_subnet_server_host_2',
    'Analyse restricted_zone_a_subnet_server_host_3',
    '[Invalid] Analyse restricted_zone_a_subnet_server_host_4',
    '[Invalid] Analyse restricted_zone_a_subnet_server_host_5',
    'Analyse restricted_zone_a_subnet_user_host_0',
    'Analyse restricted_zone_a_subnet_user_host_1',
    'Analyse restricted_zone_a_subnet_user_host_2',
    'Analyse restricted_zone_a_subnet_user_host_3',
    'Analyse restricted_zone_a_subnet_user_host_4',
    'Analyse restricted_zone_a_subnet_user_host_5',
    '[Invalid] Analyse restricted_zone_a_subnet_user_host_6',
    '[Invalid] Analyse restricted_zone_a_subnet_user_host_7',
    '[Invalid] Analyse restricted_zone_a_subnet_user_host_8',
    '[Invalid] Analyse restricted_zone_a_subnet_user_host_9',
    'Monitor',
    'Remove restricted_zone_a_subnet_server_host_0',
    'Remove restricted_zone_a_subnet_server_host_1',
    'Remove restricted_zone_a_subnet_server_host_2',
    'Remove restricted_zone_a_subnet_server_host_3',
    '[Invalid] Remove restricted_zone_a_subnet_server_host_4',
    '[Invalid] Remove restricted_zone_a_subnet_server_host_5',
    'Remove restricted_zone_a_subnet_user_host_0',
    'Remove restricted_zone_a_subnet_user_host_1',
    'Remove restricted_zone_a_subnet_user_host_2',
    'Remove restricted_zone_a_subnet_user_host_3',
    'Remove restricted_zone_a_subnet_user_host_4',
    'Remove restricted_zone_a_subnet_user_host_5',
    '[Invalid] Remove restricted_zone_a_subnet_user_host_6',
    '[Invalid] Remove restricted_zone_a_subnet_user_host_7',
    '[Invalid] Remove restricted_zone_a_subnet_user_host_8',
    '[Invalid] Remove restricted_zone_a_subnet_user_host_9',
    'Restore restricted_zone_a_subnet_server_host_0',
    'Restore restricted_zone_a_subnet_server_host_1',
    'Restore restricted_zone_a_subnet_server_host_2',
    'Restore restricted_zone_a_subnet_server_host_3',
    '[Invalid] Restore restricted_zone_a_subnet_server_host_4',
    '[Invalid] Restore restricted_zone_a_subnet_server_host_5',
    'Restore restricted_zone_a_subnet_user_host_0',
    'Restore restricted_zone_a_subnet_user_host_1',
    'Restore restricted_zone_a_subnet_user_host_2',
    'Restore restricted_zone_a_subnet_user_host_3',
    'Restore restricted_zone_a_subnet_user_host_4',
    'Restore restricted_zone_a_subnet_user_host_5',
    '[Invalid] Restore restricted_zone_a_subnet_user_host_6',
    '[Invalid] Restore restricted_zone_a_subnet_user_host_7',
    '[Invalid] Restore restricted_zone_a_subnet_user_host_8',
    '[Invalid] Restore restricted_zone_a_subnet_user_host_9',
    'Sleep',
    'AllowTrafficZone restricted_zone_a_subnet (10.0.215.0/24) <- admin_network_subnet (10.0.78.0/24)',
    'AllowTrafficZone restricted_zone_a_subnet (10.0.215.0/24) <- contractor_network_subnet (10.0.21.0/24)',
    'AllowTrafficZone restricted_zone_a_subnet (10.0.215.0/24) <- internet_subnet (10.0.137.0/24)',
    'AllowTrafficZone restricted_zone_a_subnet (10.0.215.0/24) <- office_network_subnet (10.0.106.0/24)',
    'AllowTrafficZone restricted_zone_a_subnet (10.0.215.0/24) <- operational_zone_a_subnet (10.0.170.0/24)',
    'AllowTrafficZone restricted_zone_a_subnet (10.0.215.0/24) <- operational_zone_b_subnet (10.0.57.0/24)',
    'AllowTrafficZone restricted_zone_a_subnet (10.0.215.0/24) <- public_access_zone_subnet (10.0.243.0/24)',
    'AllowTrafficZone restricted_zone_a_subnet (10.0.215.0/24) <- restricted_zone_b_subnet (10.0.123.0/24)',
    'BlockTrafficZone restricted_zone_a_subnet (10.0.215.0/24) <- admin_network_subnet (10.0.78.0/24)',
    'BlockTrafficZone restricted_zone_a_subnet (10.0.215.0/24) <- contractor_network_subnet (10.0.21.0/24)',
    'BlockTrafficZone restricted_zone_a_subnet (10.0.215.0/24) <- internet_subnet (10.0.137.0/24)',
    'BlockTrafficZone restricted_zone_a_subnet (10.0.215.0/24) <- office_network_subnet (10.0.106.0/24)'

In [8]:
actions = { "blue_agent_0": 42 }
obs, reward, terminated, truncated, info = env.step(actions)

In [14]:
print(obs)

{
    'blue_agent_2': {
        'success': <TernaryEnum.UNKNOWN: 2>,
        'action': Sleep,
        'message': [
            array([False, False, False, False, False, False, False, False]),
            array([False, False, False, False, False, False, False, False]),
            array([False, False, False, False, False, False, False, False]),
            array([False, False, False, False, False, False, False, False])
        ]
    },
    'blue_agent_3': {
        'success': <TernaryEnum.UNKNOWN: 2>,
        'action': Sleep,
        'message': [
            array([False, False, False, False, False, False, False, False]),
            array([False, False, False, False, False, False, False, False]),
            array([False, False, False, False, False, False, False, False]),
            array([False, False, False, False, False, False, False, False])
        ]
    },
    'blue_agent_1': {
        'success': <TernaryEnum.UNKNOWN: 2>,
        'action': Sleep,
        'message': [
            array([False, False, False, False, False, False, False, False]),
            array([False, False, False, False, False, False, False, False]),
            array([False, False, False, False, False, False, False, False]),
            array([False, False, False, False, False, False, False, False])
        ]
    },
    'blue_agent_4': {
        'success': <TernaryEnum.UNKNOWN: 2>,
        'action': Sleep,
        'message': [
            array([False, False, False, False, False, False, False, False]),
            array([False, False, False, False, False, False, False, False]),
            array([False, False, False, False, False, False, False, False]),
            array([False, False, False, False, False, False, False, False])
        ]
    },
    'blue_agent_0': {
        'success': <TernaryEnum.IN_PROGRESS: 4>,
        'message': [
            array([False, False, False, False, False, False, False, False]),
            array([False, False, False, False, False, False, False, False]),
            array([False, False, False, False, False, False, False, False]),
            array([False, False, False, False, False, False, False, False])
        ]
    }
}